[package]
name = "gist_21"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.226", default-features = false, features = ["derive"] }
serde_json = "1.0.145"
url = {version = "2.5.7", features = ["serde"] }
